config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :common_codes
  resources :presentations
  resources :users

  namespace :api do
    resources :categories, only: [:index]
    resources :categories, only: :index do
      collection do
        get :presentations
      end
    end
    resources :favorites, only: :index
    resources :teams, only: [:index] do
      collection do
        get :presentations
      end
    end
    resources :presentations, only: [:index, :show]
    resources :presentations, only: [:show] do
      resources :comments
      post :thumbsup
      post :thumbsdown
    end
    resources :users, only: :index do
      collection do
        get :presentations
        get :favorite_presentations
        post :modify
        post :authentication
        post :signup
        post :signin
      end
    end
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/presentation.rb
class Presentation < ApplicationRecord
  belongs_to :user, counter_cache: true
  has_many :images, as: :imageable
  has_one :video
  has_one :pdf
  has_many :comments
  has_one :presentation_view
  has_many :favorites

  scope :find_by_category, lambda { |category|
    where(category_id: category) if category.present?
  }

  scope :find_by_user, lambda { |user|
    where(user_id: user) if user.present?
  }

  scope :top5, -> {
    select("presentations.presentation_id, count(favorites.favorite_id) AS favorites_count").
    joins(:favorites).
    where("favorites.created_at >= ?", 7.day.ago).
    group("presentations.presentation_id").
    order("favorites_count DESC").
    limit(5)
  }

  def get_category_name(category_id)
  	CommonCode.find_by_category(category_id).first.name_korean
  end
end

app/models/presentation_view.rb
class PresentationView < ApplicationRecord
  belongs_to :presentation

  def self.find_by_presentation_id(presentation_id)
    find_by(presentation_id: presentation_id).nil? if presentation_id.present?
  end
end

app/controllers/api/presentations_controller.rb
class Api::PresentationsController < ApplicationController

  before_action :set_presentation, only: [:show, :edit]
  before_action :set_prensentation_with_thumbs, only: [:thumbsup, :thumbsdown]
  skip_before_filter :verify_authenticity_token, only: [:thumbsup, :thumbsdown]

  respond_to :json

  # GET api/presentations.json
  def index
    @presentations = Presentation.find_by_category(params[:category_id])
                     .find_by_user(params[:user_id])
                     .order(created_at: :desc)
    respond_with(@presentations)
  end

  # GET api/presentations/1.json
  def show
    # 수정필요 
    # @presentation.presentation_view.increment_counter :view_count, @presentation.presentation_id
    Presentation.transaction do
      PresentationView.increment_counter :view_count, @presentation.presentation_view.presentation_view_id
      @favorite_presentation = @presentation.favorites.find_by(user_id: params[:user_id]).present?
    end
    respond_with(@presentation)
  end

  # POST api/presentation/1/thumbsup.json?user_id=1
  def thumbsup
    @favorite = @presentation.favorites.new(user_id: params[:user_id])
    @favorite.save
  end

  # POST api/presentation/1/thumbsdown.json?user_id=1
  def thumbsdown
    @presentation.favorites.find_by(user_id: params[:user_id]).destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presentation
      @presentation = Presentation.find(params[:id])
    end

    def set_prensentation_with_thumbs
      @presentation = Presentation.find(params[:presentation_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def presentation_params
      params.require(:presentation).permit(
        :user_id, :title, :subtitle, :content, :video, :pdf
      )
    end
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  include VideoHelper
  include PdfHelper

  before_action :set_presentation, only: [:show, :edit, :update, :destroy]
  before_action :find_by_category

  respond_to :html, :json

  # GET /presentations
  # GET /presentations.json
  def index
    @presentations = Presentation.all
    respond_with(@presentations)
  end

  # GET /presentations/1
  # GET /presentations/1.json
  def show
    respond_with(@presentation)
  end

  # GET /presentations/new
  def new
    @presentation = Presentation.new
    respond_with(@presentation)
  end

  # GET /presentations/1/edit
  def edit
  end

  # POST /presentations
  # POST /presentations.json
  def create
    @presentation = Presentation.new(presentation_params)
    @presentation.save
    if params.has_key?(:video)
      VideoHelper.create_single_video(params[:video], @presentation.id)  
    end
    if params.has_key?(:pdf)
      PdfHelper.create_single_pdf(params[:pdf], @presentation.id)
      PdfHelper.convert(@presentation.pdf, @presentation)  
    end
    @presentation_view = PresentationView.new(:presentation_id => @presentation.presentation_id)
    @presentation_view.save
    respond_with(@presentation)
  end

  # PATCH/PUT /presentations/1
  # PATCH/PUT /presentations/1.json
  def update
    @presentation.update(presentation_params)
    if params.has_key?(:video)
      VideoHelper.update_single_video(params[:video], @presentation.id)
    end
    if params.has_key?(:pdf)
      PdfHelper.update_single_pdf(params[:pdf], @presentation.id)
      PdfHelper.convert(@presentation.pdf, @presentation)
    end
    respond_with(@presentation)
  end

  # DELETE /presentations/1
  # DELETE /presentations/1.json
  def destroy
    @presentation.presentation_view.delete
    @presentation.destroy
    if @presentation.video.present?
      VideoHelper.delete_single_video(@presentation.id)  
    end
    if @presentation.pdf.present?
      PdfHelper.delete_single_pdf(@presentation.id)
    end
    respond_with(@presentation)
  end

  private
    def find_by_category
      @category = CommonCode.find_by_common_code_type('CATEGORY')
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_presentation
      @presentation = Presentation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def presentation_params
      params.require(:presentation).permit(
        :user_id, :category_id, :title, :subtitle, :content, :video, :pdf
      )
    end
end

app/helpers/presentations_helper.rb
module PresentationsHelper
end

app/views/presentations/_form.html.erb
<%= form_for @presentation, html: { multipart: true } do |f| %>
  <% if presentation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(presentation.errors.count, "error") %> prohibited this presentation from being saved:</h2>

      <ul>
      <% presentation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :video %>
    <%= file_field_tag :video %>
  </div>

  <div class="field">
    <%= f.label :pdf %>
    <%= file_field_tag :pdf %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :category_id %>
    <% options = options_from_collection_for_select(@category, 'common_code_detail_id', 'name_korean') %>
    <%= f.select :category_id,  options %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_area :title %>
  </div>

  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_area :subtitle %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/presentations/edit.html.erb
<h1>Editing Presentation</h1>

<%= render 'form', presentation: @presentation %>

<%= link_to 'Show', @presentation %> |
<%= link_to 'Back', presentations_path %>

app/views/presentations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Presentations</h1>

<table>
  <thead>
    <tr>
      <th>Presentation_id</th>
      <th>Video_thumbnail</th>
      <th>User_id</th>
      <th>Category</th>
      <th>Title</th>
      <th>Subtitle</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @presentations.each do |presentation| %>
      <tr>
        <td><%= presentation.id %></td>
        <td align="center">
          <% if presentation.video.present? %>
            <img src= <%= presentation.video.video.url(:thumb) %> width="100" height="100">
          <% else %>
            이미지 없음
          <% end %> 
          
        </td>
        <td><%= presentation.user.user_id %></td>
        <td><%= CommonCode.find_by_category(presentation.category_id).first.name_korean %></td>
        <td><%= presentation.title %></td>
        <td><%= presentation.subtitle %></td>
        <td><%= presentation.content %></td>
        <td><%= link_to 'Show', presentation %></td>
        <td><%= link_to 'Edit', edit_presentation_path(presentation) %></td>
        <td><%= link_to 'Destroy', presentation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Presentation', new_presentation_path %>

app/views/presentations/new.html.erb
<h1>New Presentation</h1>

<%= render 'form', presentation: @presentation %>

<%= link_to 'Back', presentations_path %>

app/views/presentations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @presentation.user %>
</p>

<p>
  <strong>Category id:</strong>
  <%= @presentation.category_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @presentation.title %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @presentation.subtitle %>
</p>

<p>
  <strong>Content:</strong>
  <%= @presentation.content %>
</p>

<%= link_to 'Edit', edit_presentation_path(@presentation) %> |
<%= link_to 'Back', presentations_path %>