config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :common_codes
  resources :presentations
  resources :users

  namespace :api do
    resources :categories, only: [:index]
    resources :categories, only: :index do
      collection do
        get :presentations
      end
    end
    resources :favorites, only: :index
    resources :teams, only: [:index] do
      collection do
        get :presentations
      end
    end
    resources :presentations, only: [:index, :show]
    resources :presentations, only: [:show] do
      resources :comments
      post :thumbsup
      post :thumbsdown
    end
    resources :users, only: :index do
      collection do
        get :presentations
        get :favorite_presentations
        post :modify
        post :authentication
        post :signup
        post :signin
      end
    end
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/common_code.rb
class CommonCode < ApplicationRecord
  def self.find_by_category(category_id)
    find_by_common_code('CATEGORY', category_id)
  end

  def self.find_by_team(team_id)
    find_by_common_code('TEAM', team_id)
  end

  def self.find_by_common_code(common_code_type, common_code_detail_id)
    find_by_common_code_type(common_code_type).find_by_common_code_detail_id(common_code_detail_id)
  end

  def self.find_by_common_code_type(common_code_type)
    where(common_code_type: common_code_type)
  end

  def self.find_by_common_code_detail_id(common_code_detail_id)
    where(common_code_detail_id: common_code_detail_id)
  end
end

app/controllers/common_codes_controller.rb
class CommonCodesController < ApplicationController
  before_action :set_common_code, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  # GET /common_codes
  # GET /common_codes.json
  def index
    @common_codes = CommonCode.all
    respond_with(@presentations)
  end

  # GET /common_codes/1
  # GET /common_codes/1.json
  def show
    respond_with(@presentation)
  end

  # GET /common_codes/new
  def new
    @common_code = CommonCode.new
    respond_with(@presentation)
  end

  # GET /common_codes/1/edit
  def edit
  end

  # POST /common_codes
  # POST /common_codes.json
  def create
    @common_code = CommonCode.new(common_code_params)
    @common_code.save
    respond_with(@presentation)
  end

  # PATCH/PUT /common_codes/1
  # PATCH/PUT /common_codes/1.json
  def update
    @common_code.update(common_code_params)
    respond_with(@presentation)
  end

  # DELETE /common_codes/1
  # DELETE /common_codes/1.json
  def destroy
    @common_code.destroy
    respond_with(@presentation)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_common_code
      @common_code = CommonCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def common_code_params
      params.require(:common_code).permit(
        :common_code_type, :common_code_detail_id, :name_korean, :yn_use
      )
    end
end

app/helpers/common_codes_helper.rb
module CommonCodesHelper
end

app/views/common_codes/_form.html.erb
<%= form_for(common_code) do |f| %>
  <% if common_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(common_code.errors.count, "error") %> prohibited this common_code from being saved:</h2>

      <ul>
      <% common_code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :common_code_type %>
    <%= f.text_area :common_code_type %>
  </div>

  <div class="field">
    <%= f.label :common_code_detail_id %>
    <%= f.number_field :common_code_detail_id %>
  </div>

  <div class="field">
    <%= f.label :name_korean %>
    <%= f.text_area :name_korean %>
  </div>

  <div class="field">
    <%= f.label :yn_use %>
    <%= f.check_box :yn_use %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/common_codes/edit.html.erb
<h1>Editing Common Code</h1>

<%= render 'form', common_code: @common_code %>

<%= link_to 'Show', @common_code %> |
<%= link_to 'Back', common_codes_path %>

app/views/common_codes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Common Codes</h1>

<table>
  <thead>
    <tr>
      <th>Common code id</th>
      <th>Common code type</th>
      <th>Common code detail</th>
      <th>Name korean</th>
      <th>Yn use</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @common_codes.each do |common_code| %>
      <tr>
        <td><%= common_code.common_code_id %></td>
        <td><%= common_code.common_code_type %></td>
        <td><%= common_code.common_code_detail_id %></td>
        <td><%= common_code.name_korean %></td>
        <td><%= common_code.yn_use %></td>
        <td><%= link_to 'Show', common_code %></td>
        <td><%= link_to 'Edit', edit_common_code_path(common_code) %></td>
        <td><%= link_to 'Destroy', common_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Common Code', new_common_code_path %>

app/views/common_codes/new.html.erb
<h1>New Common Code</h1>

<%= render 'form', common_code: @common_code %>

<%= link_to 'Back', common_codes_path %>

app/views/common_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Common code type:</strong>
  <%= @common_code.common_code_type %>
</p>

<p>
  <strong>Common code detail:</strong>
  <%= @common_code.common_code_detail_id %>
</p>

<p>
  <strong>Name korean:</strong>
  <%= @common_code.name_korean %>
</p>

<p>
  <strong>Yn use:</strong>
  <%= @common_code.yn_use %>
</p>

<%= link_to 'Edit', edit_common_code_path(@common_code) %> |
<%= link_to 'Back', common_codes_path %>